# ==========================================
# データベース接続設定 (自動作成オプション付き)
# ==========================================
# 「/diet_db」の前に、存在しなければ自動で作る設定を組み込んでいます
spring.datasource.url=jdbc:mysql://database-1.c3uiu3zg691r.us-east-1.rds.amazonaws.com:3306/diet_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo

# AWS RDSのユーザー名
spring.datasource.username=admin

# AWS RDSを作成したときにあなたが決めたパスワード
spring.datasource.password=pbl5hanaws

# ドライバー・方言設定
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# テーブルを自動作成・更新する設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true